[tool.poetry]
name = "club_house_api"
version = "1.0"
description = 'Python module for writing scripts for project management platform Club House (clubhouse.io API wrapper)'
authors = ["Peopl3s"]
license = "Apache License, Version 2.0"
readme = "README.md"
homepage = "https://github.com/Peopl3s/club-house-api"
repository = "https://github.com/Peopl3s/club-house-api"
keywords = ["python", "async", "python3", "clubhouse", "clubhouse-api", "api-wrapper", "async-clubhouse-api"]
classifiers = [
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Developers',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Programming Language :: Python :: Implementation :: CPython',
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Peopl3s/club-house-api/issues"

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.7.3"
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]

# Tests
pytest = "^6.2"
pytest-asyncio = "^0.14.0"
pytest-mock = "^3.5.1"
mock = "^4.0.3"

[tool.black]
line-length = 99
target-version = ['py37', 'py38']
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99

[build-system]
requires = ["poetry>=0.12", "setuptools"]
build-backend = "poetry.masonry.api"